export const slideData = {
  woman: [
    {
      name: "자수 코튼 포플린 셔츠",
      price: "2,900,000원",
      season: "2025 프리폴 컬렉션",
      imgDefault: "../resources/images/component/studio/woman/1.avif",
      imgHover: "../resources/images/component/studio/woman/1-2.avif",
    },
    {
      name: "GG 크레이프 실크 울 더블 브레스트 코트",
      price: "12,200,000원",
      season: "2025 봄 여름 컬렉션",
      imgDefault: "../resources/images/component/studio/woman/2.avif",
      imgHover: "../resources/images/component/studio/woman/2-2.avif",
    },
    {
      name: "홀스빗 데님 미니 드레스",
      price: "3,600,000원",
      season: "2025 크루즈 컬렉션",
      imgDefault: "../resources/images/component/studio/woman/3.avif",
      imgHover: "../resources/images/component/studio/woman/3-2.avif",
    },
    {
      name: "웹(Web) 코튼 포플린 드레스",
      price: "2,700,000원",
      imgDefault: "../resources/images/component/studio/woman/4.avif",
      imgHover: "../resources/images/component/studio/woman/4-2.avif",
    },
    {
      name: "홀스빗 GG 캔버스 재킷",
      price: "4,100,000원",
      season: "GG 모노그램 컬렉션",
      imgDefault: "../resources/images/component/studio/woman/5.avif",
      imgHover: "../resources/images/component/studio/woman/5-2.avif",
    },
    {
      name: "프린트 디테일의 코튼 저지 스웨트셔츠",
      price: "1,700,000원",
      imgDefault: "../resources/images/component/studio/woman/6.avif",
      imgHover: "../resources/images/component/studio/woman/6-2.avif",
    },
  ],
  man: [
    {
      name: "자수 코튼 포플린 셔츠",
      price: "1,470,000원",
      season: "2025 프리폴 컬렉션",
      imgDefault: "../resources/images/component/studio/man/1.avif",
      imgHover: "../resources/images/component/studio/man/1-2.avif",
    },
    {
      name: "웹(Web) 디테일의 니트 코튼 V 넥 가디건",
      price: "2,240,000원",
      imgDefault: "../resources/images/component/studio/man/2.avif",
      imgHover: "../resources/images/component/studio/man/2-2.avif",
    },
    {
      name: "'Ancora' 자수 장식의 울 코트",
      price: "6,700,000원",
      season: "2024 가을 겨울 컬렉션",
      imgDefault: "../resources/images/component/studio/man/3.avif",
      imgHover: "../resources/images/component/studio/man/3-2.avif",
    },
    {
      name: "테크니컬 저지 후드 스웨트셔츠",
      price: "2,320,000원",
      season: "리도 컬렉션",
      imgDefault: "../resources/images/component/studio/man/4.avif",
      imgHover: "../resources/images/component/studio/man/4-2.avif",
    },
    {
      name: "인타르시아 코튼 피케 폴로 셔츠",
      price: "2,020,000원",
      season: "2025 프리폴 컬렉션",
      imgDefault: "../resources/images/component/studio/man/5.avif",
      imgHover: "../resources/images/component/studio/man/5-2.avif",
    },
    {
      name: "프린트 실크 볼링 셔츠",
      price: "1,910,000원",
      season: "2025 봄 여름 컬렉션",
      imgDefault: "../resources/images/component/studio/man/6.avif",
      imgHover: "../resources/images/component/studio/man/6-2.avif",
    },
  ],
  accessories: [
    {
      name: "우븐 미니 버킷백",
      price: "2,810,000원",
      season: "2025 크루즈 컬렉션",
      imgDefault: "../resources/images/component/studio/accessories/1.avif",
      imgHover: "../resources/images/component/studio/accessories/1-2.avif",
    },
    {
      name: "구찌 링크 투 러브 스터드 반지",
      price: "2,690,000원",
      season: "링크 투 러브(Link to Love) 컬렉션",
      imgDefault: "../resources/images/component/studio/accessories/2.avif",
      imgHover: "../resources/images/component/studio/accessories/2-2.avif",
    },
    {
      name: "GG 캔버스 라지 슬링백",
      price: "2,360,000원",
      season: "가을-겨울 남성 컬렉션",
      imgDefault: "../resources/images/component/studio/accessories/3.avif",
      imgHover: "../resources/images/component/studio/accessories/3-2.avif",
    },
    {
      name: "GG 카드 케이스 지갑",
      price: "460,000원",
      season: "2018 프리폴 컬렉션",
      imgDefault: "../resources/images/component/studio/accessories/4.avif",
      imgHover: "../resources/images/component/studio/accessories/4-2.avif",
    },
    {
      name: "엘릭서 드 퍼퓸 푸르 팜므 퍼퓸",
      price: "263,000원",
      imgDefault: "../resources/images/component/studio/accessories/5.avif",
      imgHover: "../resources/images/component/studio/accessories/5-2.avif",
    },
    {
      name: "시계, 40mm",
      price: "3,600,000원",
      imgDefault: "../resources/images/component/studio/accessories/6.avif",
      imgHover: "../resources/images/component/studio/accessories/6-2.avif",
    },
  ],
  pet: [
    {
      name: "인터로킹 G 울 블렌드 펫 스웨터",
      price: "680,000원",
      season: "러브 퍼레이드 컬렉션",
      imgDefault: "../resources/images/component/studio/pet-collection/1.avif",
      imgHover: "../resources/images/component/studio/pet-collection/1-2.avif",
    },
    {
      name: "초소형 펫 카라",
      price: "410,000원",
      season: "러브 퍼레이드 컬렉션",
      imgDefault: "../resources/images/component/studio/pet-collection/2.avif",
      imgHover: "../resources/images/component/studio/pet-collection/2-2.avif",
    },
    {
      name: "웹(Web) 스몰 GG 펫 캐리어",
      price: "4,900,000원",
      season: "러브 퍼레이드 컬렉션",
      imgDefault: "../resources/images/component/studio/pet-collection/3.avif",
      imgHover: "../resources/images/component/studio/pet-collection/3-2.avif",
    },
    {
      name: "엠보스 코튼 펫 스웨트셔츠",
      price: "690,000원",
      season: "2025 크루즈 구찌 펫 컬렉션",
      imgDefault: "../resources/images/component/studio/pet-collection/4.avif",
      imgHover: "../resources/images/component/studio/pet-collection/4-2.avif",
    },
    {
      name: "GG 웨이스트 백 홀더",
      price: "560,000원",
      season: "러브 퍼레이드 컬렉션",
      imgDefault: "../resources/images/component/studio/pet-collection/5.avif",
      imgHover: "../resources/images/component/studio/pet-collection/5-2.avif",
    },
    {
      name: "GG 펫 코트",
      price: "1,330,000원",
      season: "러브 퍼레이드 컬렉션",
      imgDefault: "../resources/images/component/studio/pet-collection/6.avif",
      imgHover: "../resources/images/component/studio/pet-collection/6-2.avif",
    },
  ],
};
